# Generated by Django 3.0.7 on 2020-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200706_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
