# Generated by Django 3.0.7 on 2020-07-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200706_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
