# Generated by Django 3.0.7 on 2020-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200706_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='comment_pics'),
        ),
    ]
